pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                sh "./springboot/mvnw compile"
            }
        }
        stage('Unit Test') {
            steps {
                sh "./springboot/mvnw test"
            }
        }
        stage('Build') {
            steps {
                sh "./springboot/mvnw package"
            }
        }
        
    }
}